name = "dbd-tracker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[observability]
[observability.logs]
enabled = true
invocation_logs = false

[vars]
FRONTEND_URL = "http://localhost:5173"

[env.production]
vars = { FRONTEND_URL = "https://macecchi.github.io/dbd-utils" }
